successfully asked name

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -439,12 +439,15 @@ declare -A repo_map=(
 )
 
 function conflict-1() {
-  cdt ../
-  git clone --bare git@github.com:department-of-veterans-affairs/[repo].git [repo]
-
-    branch_name=$1
-    repo_key=$2
-    repo=${repo_map[$repo_key]}
+  repo_key=$1
+  repo=${repo_map[$repo_key]}
+  repo_name="${repo##*/}"
+  echo $repo_name
+  echo $repo
+  cd
+  rm -rf $repo
+  git clone --bare git@github.com:department-of-veterans-affairs/$repo_name.git $repo
+  update-master $repo_key
 }
 
 function git-worktree-add() {
@@ -530,16 +533,24 @@ function workflow_check() {
 }
 
 function reset-repo() {
+    # e.g. reset-repo qa
     repo_short=$1
     repo=${repo_map[$repo_short]}
     
-    wd oddball
+    cd
     rm -rf $repo
-    git clone --bare git@github.com:department-of-veterans-affairs/$repo.git $repo
-    cd $repo
 
+    # Check if the repo is an oddball or a ~/github/ repo
+    if [[ $repo == *github/* ]]; then
+        git clone --bare git@github.com:ldraney/${repo##*/}.git $repo
+    else
+        git clone --bare git@github.com:department-of-veterans-affairs/${repo##*/}.git $repo
+    fi
+
+    cd $repo
     git-worktree-add master $repo_short
 }
+
 
 function browser() {
     /mnt/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe "$1"
@@ -597,4 +608,24 @@ function update-master() {
   git worktree add master
   cd master
   git pull origin master
+}
+
+da () {
+    if [[ -z "$1" ]]; then
+        echo "Please provide a file path."
+        return 1
+    fi
+
+    # Check if the Docker image exists
+    if ! docker image inspect my_python_app > /dev/null 2>&1; then
+        echo "Image not found locally. Pulling..."
+        docker pull my_python_app
+    fi
+
+    # Extract directory from the provided file path
+    dir_path=$(dirname "$1")
+    file_name=$(basename "$1")
+
+    # Run the Docker container with the appropriate volume mount
+    docker run -it -e OPENAI_API_KEY=$OPENAI_API_KEY -v "$dir_path":/container_volume my_python_app /container_volume/"$file_name"
 }
